server:
  port: 5088
  compression:
    enabled: true

spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?characterEncoding=utf8&useSSL=true
    username: root
    password: xy19920204

  # Redis数据源
  redis:
    host: localhost
    port: 6379
    timeout: 6000
#    password: as123456
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接

mybatis:
  mapper-locations: classpath:mybatis/*.xml # 注意一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xy.spring.demo.entity # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true # 数据库字段下划线自动转驼峰